package com.MedievalMedia.Controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.util.UriComponentsBuilder;

import com.MedievalMedia.Records.PaymentRequest;
import com.MedievalMedia.Services.PaypalService;
import com.paypal.api.payments.Payment;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.PayPalRESTException;

@RestController
@RequestMapping("/paypal")
public class PayPalRestController {
	
	private PaypalService paypalService;
	private Logger log = LoggerFactory.getLogger(PayPalRestController.class);
	
	@Autowired
	public PayPalRestController() {
		this.paypalService = new PaypalService();
	}
	
	
	/**
	 * Create a payment
	 *
	 * @param request An object containing all the required informations to create a payment
	 * @return ResponseEntity with the payment object generated by PayPal
	 * @throws ResponseStatusException if payment generation failed
	 */

	@PostMapping("/create-payment")
	public ResponseEntity<Payment> createPayment(@RequestBody PaymentRequest request ) {
		try {
			
			Payment payment = this.paypalService.createPayment(request.total(), request.currency(), request.method(), request.intent(), request.description());
			return ResponseEntity.status(HttpStatus.OK).body(payment);
		} catch (PayPalRESTException e) {
			this.log.error("Error communicating with PayPal RESTApi to create payment: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
		} catch (Exception e) {
			this.log.error("Error creating payment: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
		}
	}
	
	/**
	 * Payment confirmation
	 *
	 * @param paymentId The id of the payment
	 * @param payerId The id of the payer
	 * @return ResponseEntity with the payment status code
	 * @throws ResponseStatusException if payment confirmation failed
	 */
	
	@GetMapping("/payment/success")
	public ResponseEntity<String> paymentSuccess(@RequestParam("paymentId") String paymentId, @RequestParam("payerId") String payerId) {
		try {
			Payment payment = this.paypalService.executePayment(paymentId, payerId);
			
			if (payment.getState().equals("approved")) {
				return ResponseEntity.status(HttpStatus.OK).body("Payment success");
			}
			
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Payment "+ payment.getState());
			
		} catch (PayPalRESTException e) {
			this.log.error("Error completing payment: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_GATEWAY).body("Error completing payment");
		}
	}
	
}
