package com.MedievalMedia.Controllers;

import java.math.BigDecimal;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.util.UriComponentsBuilder;

import com.MedievalMedia.Records.PaymentRequest;
import com.MedievalMedia.Records.UserRequestWithdrawPaypalDTO;
import com.MedievalMedia.Repositories.PaymentRepository;
import com.MedievalMedia.Repositories.UserRepository;
import com.MedievalMedia.Services.JwtTokenService;
import com.MedievalMedia.Services.PaymentService;
import com.MedievalMedia.Services.PaypalService;
import com.MedievalMedia.Services.UserService;
import com.paypal.api.payments.Payment;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.PayPalRESTException;

@RestController
@RequestMapping("/paypal")
public class PayPalRestController {
	
	private UserRepository userRepository;
	private PaymentRepository paymentRepository;
	private PaypalService paypalService;
	private PaymentService paymentService;
	private JwtTokenService jwtService;
	private UserService userService;
	private Logger log = LoggerFactory.getLogger(PayPalRestController.class);
	
	@Autowired
	public PayPalRestController(UserRepository userRepository) {
		this.userRepository = userRepository;
		this.paypalService = new PaypalService(this.userRepository);
		this.paymentService = new PaymentService(this.paymentRepository);
		this.jwtService = new JwtTokenService();
		this.userService = new UserService(userRepository);
	}
	
	
	/**
	 * Create a payment
	 *
	 * @param request An object containing all the required informations to create a payment
	 * @return ResponseEntity with the payment object generated by PayPal or the http status if the petition has failed
	 * 
	 * Possible http codes:
	 * 
	 * 	200: if the payment was successful created
	 *  400: if an communication error with paypal api occured
	 * 	500: if an unknown server error occurred
	 */

	@PostMapping("/create-payment")
	public ResponseEntity<Payment> createPayment(@RequestBody PaymentRequest request ) {
		try {
			
			Payment payment = this.paypalService.createPayment(request.total(), request.currency(), request.description());
			return ResponseEntity.status(HttpStatus.OK).body(payment);
		} catch (PayPalRESTException e) {
			this.log.error("Error communicating with PayPal RESTApi to create payment: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
		} catch (Exception e) {
			this.log.error("Error creating payment: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
		}
	}
	
	/**
	 * Payment confirmation
	 *
	 * @param paymentId The id of the payment
	 * @param payerId The id of the payer
	 * @return ResponseEntity with the payment status code
	 * 
	 * Possible http codes:
	 * 
	 *  200: if the payment was successful confirmed
	 * 	409: if the payment was not approved. The payment status is accessible through the body
	 * 	509: if an error with paypal api occured
	 * 	500: if an unknown server error occurred
	 */
	
	@GetMapping("/payment/success")
	public ResponseEntity<String> paymentSuccess(@RequestParam("paymentId") String paymentId, @RequestParam("payerId") String payerId) {
		try {
			Payment payment = this.paypalService.executePayment(paymentId, payerId);
			
			if (payment.getState().equals("approved")) {
				return ResponseEntity.status(HttpStatus.OK).body("Payment success");
			}
			
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Payment "+ payment.getState());
			
		} catch (PayPalRESTException e) {
			this.log.error("Error completing payment: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_GATEWAY).body("Error completing payment");
		} catch (Exception e) {
			this.log.error("Unknow error completing payment: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error completing payment");
		}
	}
	
	
}
