package com.MedievalMedia.Controllers;

import java.math.BigDecimal;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.util.UriComponentsBuilder;

import com.MedievalMedia.Records.PaymentRequest;
import com.MedievalMedia.Records.UserRequestWithdrawPaypalDTO;
import com.MedievalMedia.Repositories.PaymentRepository;
import com.MedievalMedia.Repositories.UserRepository;
import com.MedievalMedia.Services.JwtTokenService;
import com.MedievalMedia.Services.PaymentService;
import com.MedievalMedia.Services.PaypalService;
import com.MedievalMedia.Services.UserService;
import com.paypal.api.payments.Payment;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.PayPalRESTException;

@RestController
@RequestMapping("/paypal")
public class PayPalRestController {
	
	private UserRepository userRepository;
	private PaymentRepository paymentRepository;
	private PaypalService paypalService;
	private PaymentService paymentService;
	private JwtTokenService jwtService;
	private UserService userService;
	private Logger log = LoggerFactory.getLogger(PayPalRestController.class);
	
	@Autowired
	public PayPalRestController(UserRepository userRepository) {
		this.userRepository = userRepository;
		this.paypalService = new PaypalService(this.userRepository);
		this.paymentService = new PaymentService(this.paymentRepository);
		this.jwtService = new JwtTokenService();
		this.userService = new UserService(userRepository);
	}
	
	
	/**
	 * Create a payment
	 *
	 * @param request An object containing all the required informations to create a payment
	 * @return ResponseEntity with the payment object generated by PayPal or the http status if the petition has failed
	 * 
	 * Possible http codes:
	 * 
	 * 	200: if the payment was successful created
	 *  400: if an communication error with Paypal api occurred
	 *  401: if user is not authenticated
	 *  406: if the payment creation failed
	 * 	500: if an unknown server error occurred
	 */

	@PostMapping("/create-payment")
	public ResponseEntity<String> createPayment(@RequestBody PaymentRequest request, HttpRequest httpRequest) {
		try {
			String token = httpRequest.getHeaders().get("Authorize").toString().replace("Bearer ", "");
			
			if (!this.jwtService.validateToken(token)) {
				return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
			}
						
			Payment payment = this.paypalService.createPayment(request.total(), request.currency(), request.description());
			
			if (payment.getState() == "created") {
				UUID userId = this.userService.getCurrentUserId(this.jwtService.extractEmail(token));
				this.paymentService.createInternalPayment(userId.toString(), request.total(), payment.getId());
				
				String approvalUrl = payment.getLinks()
					    .stream()
					    .filter(link -> "approval_url".equals(link.getRel()))
					    .findFirst()
					    .map(link -> link.getHref())
					    .orElseThrow(() -> new RuntimeException("Approval URL not found"));
				
				return ResponseEntity.status(HttpStatus.OK).body(approvalUrl);
			}
			
			return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body("Payment was not approved. Current status: " + payment.getState());
			
		} catch (PayPalRESTException e) {
			this.log.error("Error communicating with PayPal RESTApi to create payment: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
		} catch (Exception e) {
			this.log.error("Error creating payment: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
		}
	}
	
	/**
	 * Payment confirmation
	 *
	 * @param paymentId The id of the payment
	 * @param payerId The id of the payer
	 * @return ResponseEntity with the payment status code
	 * 
	 * Possible http codes:
	 * 
	 *  200: if the payment was successful confirmed
	 * 	409: if the payment was not approved. The payment status is accessible through the body
	 * 	502: if an error with Paypal api occured
	 * 	500: if an unknown server error occurred
	 */
	
	@GetMapping("/payment/success")
	public ResponseEntity<String> paymentSuccess(@RequestParam("paymentId") String paymentId, @RequestParam("payerId") String payerId, HttpRequest request) {
		try {
			
			Payment payment = this.paypalService.executePayment(paymentId, payerId);
			
			if (payment.getState().equals("approved")) {
				this.paymentService.updatePaymentStatus(paymentId);
				return ResponseEntity.status(HttpStatus.OK).body("Payment success");
			}
			
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Payment "+ payment.getState());
			
		} catch (PayPalRESTException e) {
			this.log.error("Error completing payment: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_GATEWAY).body("Error completing payment");
		} catch (Exception e) {
			this.log.error("Unknow error completing payment: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error completing payment");
		}
	}
	
	/**
	 *  Cancel a payment
	 * 
	 * @param paymentId
	 * @return ResponseEntity It contains the http status code and an explaining message
	 * 
	 * Possible http codes:
	 * 
	 *  200: if the payment was successful canceled
	 *  401: if user is not authenticated
	 *  403: if user doesn't match the payment creator
	 *  404: if the payment was not found
	 * 	500: if an unknown server error occurred
	 */
	@GetMapping("/payment/cancel")
	public ResponseEntity<String> cancelPayment(@RequestParam("paymentId") String paymentId, HttpRequest request) {
		try {
			String token = request.getHeaders().get("Authorize").toString().replace("Bearer ", "");
			
			if (!this.jwtService.validateToken(token)) {
				return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User must be authenticated to fullfil this action");
			}
			
			UUID userId = this.userService.getCurrentUserId(this.jwtService.extractEmail(token));
			
			this.paymentService.cancelPayment(paymentId, userId);
			
			return ResponseEntity.status(HttpStatus.OK).body("Payment was canceled");
		} catch (ResponseStatusException e) {
			this.log.error("Error canceling payment: " + e);
			
			return ResponseEntity.status(e.getStatusCode()).body(e.getBody().toString());
		} catch (Exception e) {
			this.log.error("Unknow error canceling payment: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error canceling payment");
		}
	}
	
	/**
	 * Endpoint to request a withdraw through Paypal
	 * 
	 * @param withdraw An DTO object containing the payment information
	 * @param request To access authorization token
	 * @return ResponseEntity It contains the http status and an explaining message
	 * 
	 * Possible http codes:
	 * 
	 *  200: if the withdraw was successful requested
	 *  401: if the user isn't authenticated
	 * 	502: if the communication with Paypal api was interrupted
	 * 	500: if an unknown server error occurred
	 */
	
	@PostMapping("/request-withdraw")
	public ResponseEntity<String> requestWithdraw(@RequestBody UserRequestWithdrawPaypalDTO withdraw, HttpRequest request) {
		try {
			String token = request.getHeaders().get("Authorize").toString().replace("Bearer ", "");
			
			if (!this.jwtService.validateToken(token)) {
				return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User must be authenticated to fullfil this action");
			}
			
			UUID userId = this.userService.getCurrentUserId(this.jwtService.extractEmail(token));
			
			this.paypalService.withdrawPayment(userId, withdraw.value(), withdraw.userPaypalId(), "USD");
			
			return ResponseEntity.status(HttpStatus.OK).body("Withdraw was successful requested");
		} catch (ResponseStatusException e) {
			this.log.error("Error while requesting withdraw: " + e);
			
			return ResponseEntity.status(e.getStatusCode()).body(e.getBody().toString());
		} catch (InterruptedException e) {
			this.log.error("Error while communicating with Paypal API to request a withdraw: " + e);
			
			return ResponseEntity.status(HttpStatus.BAD_GATEWAY).body("Error while communicating with Paypal API to request a withdraw");
		} catch (Exception e) {
			this.log.error("Unknow error while requesting withdraw: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error while requesting withdraw");
		}
	}
	
}
