package com.MedievalMedia.Controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

import com.MedievalMedia.Records.PixRequestDTO;
import com.MedievalMedia.Records.WithdrawDTO;
import com.MedievalMedia.Repositories.PaymentRepository;
import com.MedievalMedia.Repositories.UserRepository;
import com.MedievalMedia.Services.JwtTokenService;
import com.MedievalMedia.Services.PixService;

@RestController
@RequestMapping("/pix/")
public class PixRestController {
	private PaymentRepository paymentRepository;
	private UserRepository userRepository;
	private PixService pixService;
	private JwtTokenService jwtService;
	private Logger log = LoggerFactory.getLogger(PixRestController.class);
	
	
	
	public PixRestController(PaymentRepository paymentRepository, UserRepository userRepository) {
		this.paymentRepository = paymentRepository;
		this.userRepository = userRepository;
		this.pixService = new PixService(this.paymentRepository, this.userRepository);
		this.jwtService = new JwtTokenService();
	}

	/**
	 * Create a payment
	 *
	 * @param pix An object containing a pixDTO with the payment information, the id of the donator, the id of the receiver, and the interaction
	 * @param request Access headers to verify jwt token
	 * @return ResponseEntity with the payment object generated by PayPal
	 * @throws ResponseStatusException if payment generation failed
	 */
	@PostMapping("/create-payment")
	public ResponseEntity<String> createPayment(@RequestBody PixRequestDTO pix, HttpRequest request) {
		try {
			String token = request.getHeaders().get("Authorization").toString().replace("Bearer: ", "");
			
			if (!this.jwtService.validateToken(token)) {
				throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "You must be loged in to donate");
			}
			
			String link = this.pixService.createQRCode(pix.pix(), pix.payerId(), pix.finalUserId(), pix.donationType());
			
			return ResponseEntity.status(HttpStatus.OK).body(link);
		} catch (ResponseStatusException e) {
			this.log.error("Error creating pix qr code payment " + e);
			
			return ResponseEntity.status(e.getStatusCode()).body(e.getBody().toString());
		} catch (Exception e) {
			this.log.error("Unknow error creating pix qr code payment " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error creating pix qr code payment");
		}
	}
	
	/**
	* Request a withdraw
    * 
	* @param transaction An WithdrawDTO record containing the user id, the money, and the pix key 
	* @return ResponseEntity The response containing the http response code and a status message
	* @throws ResponseStatusResponse containing the status code and a message
	*/
	@PostMapping("/withdraw")
	public ResponseEntity<String> withdraw(@RequestBody WithdrawDTO transaction) {
		try {
			this.pixService.withdrawPayment(transaction.userId(), transaction.money(), transaction.pixKey());
			
			return ResponseEntity.status(HttpStatus.OK).body("Success withdrawing payment with pix");
		} catch (ResponseStatusException e) {
			this.log.error("Error withdrawing payment with pix: " + e);
			
			return ResponseEntity.status(e.getStatusCode()).body("Error withdrawing payment with pix");
		}
		catch (Exception e) {
			this.log.error("Unknow error withdrawing payment with pix: " + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error withdrawing payment with pix");
		}
	}
	
	/**
	 *  Update payment status after withdraw
	 *  
	 *  @param paymentIds The ids of the payment whose status must be updated
	 *  @param request Headers to verify user
	 *  @return ResponseEntity with the status code of the response and a message. 
	 *  	OK: if payments were successful withdrawn
	 *  	UNAUTHORIZED: if the user is not authorized
	 *  	CONFLICT: if the user is not allowed to do this request
	 */
	@PostMapping("/update-withdraw")
	public ResponseEntity<String> updateWithdraw(@RequestBody List<String> paymentIds, HttpRequest request) {
		try {
			String token = request.getHeaders().get("Authorization").toString().replace("Bearer: ", "");
			
			if (!this.jwtService.validateToken(token)) {
				return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Unauthorized user");
			}
	
			if (!this.jwtService.verifyOwnership(token)) {
				return ResponseEntity.status(HttpStatus.CONFLICT).body("Invalid request");
			}
			
			this.pixService.updateWithdraw(paymentIds);
			
			return ResponseEntity.status(HttpStatus.OK).body("Payments were successful updated");
			
		} catch(Exception e) {
			this.log.error("Unknow error updating withdraw status: "  + e);
			
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Unknow error while updating withdraws");
		}
	}
}
