package com.MedievalMedia.Services;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Locale;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.util.UriComponentsBuilder;

import com.MedievalMedia.Entities.User;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.paypal.api.payments.Amount;
import com.paypal.api.payments.Payer;
import com.paypal.api.payments.Payment;
import com.paypal.api.payments.PaymentExecution;
import com.paypal.api.payments.RedirectUrls;
import com.paypal.api.payments.Transaction;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.PayPalRESTException;

@Service
public class PaypalService {
	@Value("${PAYPAL_CLIENT_ID}") private String clientId;
	@Value("${PAYPAL_CLIENT_SECRET}") private String clientSecret;
	@Value("${paypal.mode}") private String mode;
	@Value("${app.front-url}") private String frontUrl;
	
	private APIContext apiContext;
	private Logger log = LoggerFactory.getLogger(PaypalService.class);

	
	@Autowired
	public PaypalService() {
		this.apiContext = new APIContext(clientId, clientSecret, mode);
	}

	/**
	 * Create payment
	 *
	 * @param total The total value
	 * @param currency The currency which the payment will be done
	 * @param method The method that will be used to complete the transaction
	 * @param intent Specify if it is an order 
	 * @param description Payment description
	 * @return Payment The payment object generated by PayPal for this transaction
	 * @throws ResponseStatusException 
	 * 	PayPalRESTException: if payment generation failed
	 */
	public Payment createPayment(Double total, String currency, String method, String intent, String description) 
	 throws PayPalRESTException {
		this.apiContext = new APIContext(clientId, clientSecret, mode);
		this.frontUrl = this.frontUrl == null ? "http://localhost:4200" : this.frontUrl;
		String successUrl = UriComponentsBuilder.fromHttpUrl(frontUrl)
				.path("success-payment")
				.toUriString();
		String cancelUrl = UriComponentsBuilder.fromHttpUrl(frontUrl)
				.path("cancel-payment")
				.toUriString();
		
		Amount amount = new Amount();
		amount.setCurrency(currency);
		amount.setTotal(String.format(Locale.forLanguageTag(currency), "%.2f", total));
		
		Transaction transaction = new Transaction();
		transaction.setDescription(description);
		transaction.setAmount(amount);
		
		List<Transaction> transactions = new ArrayList<>();
		transactions.add(transaction);
		
		Payer payer = new Payer();
		payer.setPaymentMethod(method);
		
		
		Payment payment = new Payment();
		payment.setIntent(intent);
		payment.setPayer(payer);
		payment.setTransactions(transactions);
		
		RedirectUrls redirections = new RedirectUrls();
		redirections.setCancelUrl(cancelUrl);
		redirections.setReturnUrl(successUrl);
		
		payment.setRedirectUrls(redirections);
		
		return payment.create(apiContext);
		
	}
	
	/**
	 * Create payment
	 *
	 * @param paymentId The id of this payment
	 * @param payerId The id of the payer
	 * @return Payment The payment object generated by PayPal for this transaction
	 * @throws ResponseStatusException 
	 * 	PayPalRESTException: if payment generation failed
	 */
	
	public Payment executePayment(String paymentId, String payerId) throws PayPalRESTException {
		Payment payment = new Payment();
		payment.setId(paymentId);
		
		PaymentExecution execution = new PaymentExecution();
		execution.setPayerId(payerId);
		
		return payment.execute(this.apiContext, execution);	
	}
	
	// generate qr code 
}
